# Лабораторне заняття №2
Знайомство з бібліотекою **NumPy**.

In [140]:
import numpy

## 1 Огляд функцій випадкового вибору

### 1.1 Функція *choice*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.choice.html).

In [141]:
a = ["top", 2, "bottom", 4.5]
size = 10
probs = [0.4, 0.2, 0.1, 0.3]
replace = True
print(numpy.random.choice(a, size=size, replace=replace, p=probs))

['2' 'top' '4.5' 'top' 'bottom' 'top' 'top' '4.5' '2' '4.5']


Згенеруйте одну випадкову цифру, вважаючи їх рівноймовірними.

In [142]:
import numpy
print(numpy.random.choice(10))

4


Згенеруйте випадкову матрицю $4 \times 6$ із рівноймовірних цифр.

In [143]:
import numpy
print(numpy.random.choice(10, size=(4, 6)))

[[7 5 0 4 4 2]
 [7 8 5 5 1 9]
 [1 5 7 1 8 8]
 [3 3 3 4 7 1]]


### 1.2 Функція *randint*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.randint.html).

In [144]:
low = 0
high = 5
size = 10
print(numpy.random.randint(low=low, high=high, size=size))

[2 4 1 2 2 0 2 3 2 3]


Згенеруйте одну випадкову цифру.

In [145]:
# Місце для Вашого коду
print(numpy.random.randint(10))

6


Згенеруйте випадкову матрицю $4 \times 5$ із двоцифрових чисел.

In [146]:
# Місце для Вашого коду
print(numpy.random.randint(low = 10, high = 100, size=(4, 5)))

[[21 50 38 79 60]
 [32 40 30 33 81]
 [18 31 13 86 12]
 [37 99 24 17 57]]


### 1.3 Функція *sample*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.sample.html).

In [147]:
size = None
print(numpy.random.sample(size=size))

0.7428037456552986


Згенеруйте випадкову матрицю $3 \times 4$ із чисел з інтервалу $[0, 1)$.

In [148]:
print(numpy.random.sample(size=(3,4)))

[[0.06662696 0.92398941 0.26395847 0.36672069]
 [0.04836247 0.65313641 0.7089228  0.92879122]
 [0.336829   0.25736873 0.7260865  0.70680089]]


### 1.4 Функція *shuffle*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.shuffle.html).

In [149]:
x = numpy.arange(10)
numpy.random.shuffle(x)
print(x)

[0 7 2 4 5 3 8 6 9 1]


Перетасуйте матрицю $M$.

In [150]:
M = numpy.arange(20).reshape((4, 5))
print(M)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [151]:
numpy.random.shuffle(M)
print(M)

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


## 2 Відтворюваність результатів
Можна задати початкове значення для генератора. Це зафіксує "випадкову" послідовність.

In [152]:
print(numpy.random.randint(10))

0


In [153]:
numpy.random.seed(42)
print(numpy.random.randint(10, size=10))
print(numpy.random.choice(['t', 'r', 'b', 'l'], size=10))

[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']


## 3 Монетка

### 3.1 За допомогою функції *choice*

In [154]:
p=0.5
n=10
tosses=numpy.random.choice(["H","T"],p=[p,1-p], size=n)
print(tosses)

['H' 'H' 'H' 'H' 'T' 'H' 'H' 'T' 'H' 'H']


In [155]:
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

8 heads and 2 tails


Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [156]:
tosses = numpy.random.choice(["H","T"], size=100)
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

43 heads and 57 tails


### 3.2 За допомогою функції *randint*
Реалізуйте симуляцію підкидань монетки за допомогою функції **randint**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [157]:
tosses = numpy.random.randint(2, size=100)
print("{} heads and {} tails".format(sum(tosses == 1),sum(tosses == 0)))

43 heads and 57 tails


### 3.3 За допомогою функції *sample*
Реалізуйте симуляцію підкидань монетки за допомогою функції **sample**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [158]:
tosses = numpy.round(numpy.random.sample(100))
print("{} heads and {} tails".format(sum(tosses == 1),sum(tosses == 0)))

51 heads and 49 tails


### 3.4 Задача
Знайдіть емпіричну ймовірність герба у симуляціях підкидання монетки $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [159]:
params = [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]
for n in params:
    tosses = numpy.random.randint(2, size=n)
    heads_prob = sum(tosses == 1) / n
    tails_prob = sum(tosses == 0) / n
    print('n = {}  :  P(head) = {},  P(tail) = {}'.format(n, heads_prob, tails_prob))

n = 10  :  P(head) = 0.6,  P(tail) = 0.4
n = 50  :  P(head) = 0.44,  P(tail) = 0.56
n = 100  :  P(head) = 0.58,  P(tail) = 0.42
n = 250  :  P(head) = 0.484,  P(tail) = 0.516
n = 500  :  P(head) = 0.48,  P(tail) = 0.52
n = 1000  :  P(head) = 0.474,  P(tail) = 0.526
n = 2500  :  P(head) = 0.5128,  P(tail) = 0.4872
n = 5000  :  P(head) = 0.4928,  P(tail) = 0.5072
n = 10000  :  P(head) = 0.501,  P(tail) = 0.499


## 4 Гральний кубик
### 4.1 Реалізація симуляцій
Реалізуйте симуляцію кидків грального кубика за допомогою функції **???**. Просимулюйте $60$ кидків кубика та підрахуйте кількість кожної із сторін.

In [160]:
def find(arr, target):
  counter = 0
  for el in arr:
    if el == target:
      counter +=1
  return counter
t = numpy.random.randint(6, size=60)
print(t)
print(f'1 = {find(t, 0)} times, 2 = {find(t, 1)} times, 3 = {find(t, 2)} times')

[0 3 3 0 0 1 3 1 5 0 4 4 5 0 3 4 3 4 3 4 3 5 1 3 1 1 0 5 1 2 1 3 1 3 3 2 1
 1 4 4 0 3 2 4 1 0 2 5 1 1 5 3 3 4 4 1 1 4 5 4]
1 = 8 times, 2 = 15 times, 3 = 4 times


### 4.2 Задача
Знайдіть емпіричну ймовірність кожної сторони у симуляціях кидання грального кубика $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [161]:
n_values = [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]
for n in n_values:
    rolls = numpy.random.randint(1, 7, size=n)
    unique, counts = numpy.unique(rolls, return_counts=True)
    probabilities = counts / n
    print(f"n = {n}")
    for face, prob in zip(unique, probabilities):
        print(f"  Side {face}: {prob:.4f}")
    print()

n = 10
  Side 1: 0.1000
  Side 2: 0.4000
  Side 3: 0.3000
  Side 4: 0.1000
  Side 5: 0.1000

n = 50
  Side 1: 0.2200
  Side 2: 0.0800
  Side 3: 0.2000
  Side 4: 0.1600
  Side 5: 0.1000
  Side 6: 0.2400

n = 100
  Side 1: 0.1100
  Side 2: 0.1500
  Side 3: 0.2200
  Side 4: 0.1500
  Side 5: 0.2000
  Side 6: 0.1700

n = 250
  Side 1: 0.1800
  Side 2: 0.1520
  Side 3: 0.1560
  Side 4: 0.1920
  Side 5: 0.1720
  Side 6: 0.1480

n = 500
  Side 1: 0.1700
  Side 2: 0.1560
  Side 3: 0.1540
  Side 4: 0.1760
  Side 5: 0.1380
  Side 6: 0.2060

n = 1000
  Side 1: 0.1560
  Side 2: 0.1820
  Side 3: 0.1600
  Side 4: 0.1660
  Side 5: 0.1650
  Side 6: 0.1710

n = 2500
  Side 1: 0.1688
  Side 2: 0.1696
  Side 3: 0.1588
  Side 4: 0.1692
  Side 5: 0.1700
  Side 6: 0.1636

n = 5000
  Side 1: 0.1722
  Side 2: 0.1762
  Side 3: 0.1616
  Side 4: 0.1586
  Side 5: 0.1620
  Side 6: 0.1694

n = 10000
  Side 1: 0.1631
  Side 2: 0.1613
  Side 3: 0.1623
  Side 4: 0.1739
  Side 5: 0.1761
  Side 6: 0.1633



## 5 Колода карт
### 5.1 Реалізація

In [162]:
# Визначимо номінали, масті та карти
Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
Suits = {'♢', '♠', '♣', '♡'}
# Створимо колоду карт
Cards = [(Rank, Suit) for Rank in Ranks for Suit in Suits]
print(Cards)

[('J', '♢'), ('J', '♣'), ('J', '♡'), ('J', '♠'), ('7', '♢'), ('7', '♣'), ('7', '♡'), ('7', '♠'), ('3', '♢'), ('3', '♣'), ('3', '♡'), ('3', '♠'), ('4', '♢'), ('4', '♣'), ('4', '♡'), ('4', '♠'), ('6', '♢'), ('6', '♣'), ('6', '♡'), ('6', '♠'), ('10', '♢'), ('10', '♣'), ('10', '♡'), ('10', '♠'), ('1', '♢'), ('1', '♣'), ('1', '♡'), ('1', '♠'), ('K', '♢'), ('K', '♣'), ('K', '♡'), ('K', '♠'), ('5', '♢'), ('5', '♣'), ('5', '♡'), ('5', '♠'), ('8', '♢'), ('8', '♣'), ('8', '♡'), ('8', '♠'), ('9', '♢'), ('9', '♣'), ('9', '♡'), ('9', '♠'), ('2', '♢'), ('2', '♣'), ('2', '♡'), ('2', '♠'), ('Q', '♢'), ('Q', '♣'), ('Q', '♡'), ('Q', '♠')]


In [163]:
# Інший вівід результату
print(', '.join([(card[0] + card[1]) for card in Cards]))

J♢, J♣, J♡, J♠, 7♢, 7♣, 7♡, 7♠, 3♢, 3♣, 3♡, 3♠, 4♢, 4♣, 4♡, 4♠, 6♢, 6♣, 6♡, 6♠, 10♢, 10♣, 10♡, 10♠, 1♢, 1♣, 1♡, 1♠, K♢, K♣, K♡, K♠, 5♢, 5♣, 5♡, 5♠, 8♢, 8♣, 8♡, 8♠, 9♢, 9♣, 9♡, 9♠, 2♢, 2♣, 2♡, 2♠, Q♢, Q♣, Q♡, Q♠


In [164]:
# Або згрупувавши по мастях
for suit in Suits:
    print(", ".join([(suit+rank) for rank in Ranks]))

♢J, ♢7, ♢3, ♢4, ♢6, ♢10, ♢1, ♢K, ♢5, ♢8, ♢9, ♢2, ♢Q
♣J, ♣7, ♣3, ♣4, ♣6, ♣10, ♣1, ♣K, ♣5, ♣8, ♣9, ♣2, ♣Q
♡J, ♡7, ♡3, ♡4, ♡6, ♡10, ♡1, ♡K, ♡5, ♡8, ♡9, ♡2, ♡Q
♠J, ♠7, ♠3, ♠4, ♠6, ♠10, ♠1, ♠K, ♠5, ♠8, ♠9, ♠2, ♠Q


In [165]:
# Перемішаємо колоду
numpy.random.shuffle(Cards)

print(Cards)

[('5', '♣'), ('7', '♡'), ('8', '♡'), ('Q', '♢'), ('10', '♡'), ('8', '♢'), ('7', '♠'), ('9', '♠'), ('J', '♠'), ('Q', '♣'), ('K', '♣'), ('6', '♣'), ('6', '♢'), ('4', '♣'), ('7', '♣'), ('10', '♠'), ('3', '♡'), ('4', '♠'), ('1', '♣'), ('4', '♡'), ('1', '♡'), ('9', '♣'), ('J', '♢'), ('6', '♠'), ('3', '♢'), ('6', '♡'), ('9', '♡'), ('1', '♢'), ('K', '♡'), ('J', '♡'), ('8', '♣'), ('K', '♢'), ('J', '♣'), ('10', '♣'), ('8', '♠'), ('Q', '♠'), ('1', '♠'), ('5', '♠'), ('5', '♡'), ('2', '♣'), ('2', '♡'), ('9', '♢'), ('5', '♢'), ('10', '♢'), ('4', '♢'), ('3', '♠'), ('K', '♠'), ('3', '♣'), ('2', '♠'), ('7', '♢'), ('Q', '♡'), ('2', '♢')]


### 5.2 Задача
Знайдіть емпіричну ймовірність карти парного числа (2, 4, 6, 8, 10) у симуляціях вибору однієї карти з колоди 52 карт $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [166]:
import random
Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
Suits = {'♢', '♠', '♣', '♡'}
Cards = [(Rank, Suit) for Rank in Ranks for Suit in Suits]
n_values = [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]
even_ranks = {'2', '4', '6', '8', '10'}
for n in n_values:
    selected_cards = random.choices(Cards, k=n)
    even_count = sum(1 for rank, suit in selected_cards if rank in even_ranks)
    probability = even_count / n
    print(f"n = {n}, Probability of even card: {probability:.4f}")

n = 10, Probability of even card: 0.6000
n = 50, Probability of even card: 0.4000
n = 100, Probability of even card: 0.3900
n = 250, Probability of even card: 0.4600
n = 500, Probability of even card: 0.3920
n = 1000, Probability of even card: 0.3890
n = 2500, Probability of even card: 0.3888
n = 5000, Probability of even card: 0.3804
n = 10000, Probability of even card: 0.3803


### 5.3 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав 4 карти однієї масті та по 3 карти інших мастей. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♢7, ♢K, ♡9, ♡1, ♡5}.

In [167]:
def deal_cards():
    deck = Cards.copy()
    numpy.random.shuffle(deck)
    players = [[] for _ in range(4)]
    for i in range(4):
        suit_counts = {suit: 0 for suit in Suits}
        while len(players[i]) < 13:
            for suit in Suits:
                if suit_counts[suit] < 4 and len(players[i]) < 13:
                    for card in deck:
                        if card[1] == suit:
                            players[i].append(card)
                            deck.remove(card)
                            suit_counts[suit] += 1
                            break
            for suit in Suits:
                if suit_counts[suit] < 3 and len(players[i]) < 13:
                    for card in deck:
                        if card[1] == suit:
                            players[i].append(card)
                            deck.remove(card)
                            suit_counts[suit] += 1
                            break
    return players

players = deal_cards()
for i, hand in enumerate(players):
    print(f"Player {i+1}: {hand}")


Player 1: [('6', '♢'), ('K', '♣'), ('1', '♡'), ('K', '♠'), ('3', '♢'), ('9', '♣'), ('J', '♡'), ('1', '♠'), ('5', '♢'), ('5', '♣'), ('3', '♡'), ('8', '♠'), ('2', '♢')]
Player 2: [('7', '♢'), ('8', '♣'), ('9', '♡'), ('6', '♠'), ('4', '♢'), ('J', '♣'), ('2', '♡'), ('4', '♠'), ('1', '♢'), ('4', '♣'), ('6', '♡'), ('2', '♠'), ('J', '♢')]
Player 3: [('10', '♢'), ('3', '♣'), ('K', '♡'), ('Q', '♠'), ('Q', '♢'), ('10', '♣'), ('8', '♡'), ('7', '♠'), ('K', '♢'), ('7', '♣'), ('10', '♡'), ('5', '♠'), ('8', '♢')]
Player 4: [('9', '♢'), ('Q', '♣'), ('7', '♡'), ('3', '♠'), ('2', '♣'), ('5', '♡'), ('10', '♠'), ('6', '♣'), ('Q', '♡'), ('9', '♠'), ('1', '♣'), ('4', '♡'), ('J', '♠')]
